### ISSUE TITLE
Race condition in munin output.

### ISSUE THREAD

**Issue by hpdvanwyk** [hpdvanwyk/invertergui#19]
The munin output code sends a pointer to a struct over a channel and the immediately writes to that struct at https://github.com/diebietse/invertergui/blob/55ae241d9236eca23012c3c596b9ca85efbb153b/plugins/munin/munin.go#L125

This causes a race condition and can cause corruption in the munin output. https://github.com/diebietse/invertergui/tree/scalefixes should fix this issue.

**Comment by ncthompson** [comment]
Issue now fixed and released on v2.0.2
