### ISSUE TITLE
Invalid Input Frequency

### ISSUE THREAD

**Issue by bclermont** [hpdvanwyk/invertergui#31]
I'm so glad that I found your project: I was about to write a golang app to extract metrics from MK3-USB to feed Telegraf -> InfluxDB. 

You just save me a few days!

Just a minor UI bug, I don't have an input right now... my generator is off.

Input frequency should be `0` but it's `Inf`

![Screenshot from 2021-12-23 16-09-07](https://user-images.githubusercontent.com/474302/147291909-aa15f032-86f1-4094-91ea-d67454acea6e.png)

**Comment by ncthompson** [comment]
Sorry for the late response, everyone was away for the holidays! Thanks for the bug report, will try to get it fixed
